heat_template_version: wallaby
description: "VDU1 HOT template"

parameters:
  flavor:
    type: string
    default: u.mini.512M
  image:
    type: string
    default: jammy-base

  net1:
    type: string
    default: private
  subnet1:
    type: string
    default: private-subnet
  lb_pool:
    type: string
  lb_pool_tcp:
    type: string
    default: ""
  lb_pool_udp:
    type: string
    default: ""

  security_group:
    type: string
    default: test-secgr
  key_name:
    type: string
    default: minh
  metadata:
    type: json
    default: {}
  server_group:
    type: string
    default: ""
  root_stack_id:
    type: string
    default: ""

conditions:
  is_standalone: { equals: [{ get_param: root_stack_id }, ""] }
  has_tcp_pool: { not: { equals: [{ get_param: lb_pool_tcp }, ""] } }
  has_udp_pool: { not: { equals: [{ get_param: lb_pool_udp }, ""] } }

resources:
  VDU1:
    type: OS::Nova::Server
    depends_on: [VDU1_CP1]
    properties:
      flavor: { get_param: flavor }
      name:
        str_replace:
          template: VDU1-$last
          params:
            $last: { get_attr: [number, value, 3] }
      # image: { get_param: image } # remmember to delete volumes attached to the instance
      key_name: { get_param: key_name }
      metadata: { get_param: metadata }
      block_device_mapping:
        - delete_on_termination: true
          device_name: vda
          snapshot_id: { get_param: image }
      networks:
        - port:
            get_resource: VDU1_CP1
      scheduler_hints:
        group: { get_param: server_group }
      user_data_format: RAW
      user_data: # wait 10-15 minutes (after created) for the server to be ready
        str_replace:
          template: |
            #!/bin/bash
            echo "IP: $cp1 ----- Floating: $fip" >> /var/www/html/index.html 
            printf "---- LOGGING ----\n" >> /var/www/html/log.txt
            wc_notify_var="$wc_notify"
            printf "\n------------------\n" >> /var/www/html/log.txt
            printf "$wc_notify_var" >> /var/www/html/log.txt
            notify_cli="${wc_notify_var//0.0.0.0/172.24.4.1} --data-binary '{\"status\": \"SUCCESS\"}'"
            printf "\n------------------\n" >> /var/www/html/log.txt
            printf "$notify_cli" >> /var/www/html/log.txt
            systemctl restart apache2 

            # apt update
            # apt upgrade -y
            # sleep to stablize cpu usage
            sleep 60
            eval "$notify_cli" 

            # temporary fix for disable auto update packages
            echo "" > /etc/resolv.conf
            echo "USER DATA SETUP COMPLETED"
            exit 0
          params:
            $cp1: { get_attr: [VDU1_CP1, fixed_ips, 0, ip_address] }
            $fip: { get_attr: [VDU1_floatingIP, floating_ip_address] }
            $wc_notify: { get_attr: [wait_handle, curl_cli] }
      # availability_zone: { get_param: zone }

  wait_for_instance: # delay stack operation until instance is ready
    type: OS::Heat::WaitCondition
    properties:
      handle: { get_resource: wait_handle }
      count: 1
      timeout: 3600

  wait_handle:
    type: OS::Heat::WaitConditionHandle

  number:
    type: OS::Heat::Value
    properties:
      value:
        str_split: [".", { get_attr: [VDU1_floatingIP, floating_ip_address] }]

  # extVL with numDynamicAddresses and subnet
  VDU1_CP1:
    type: OS::Neutron::Port
    properties:
      network: { get_param: net1 }
      fixed_ips:
        - subnet: { get_param: subnet1 }
      security_groups: [{ get_param: security_group }]

  # HTTP Load Balancer Member
  LB_member:
    type: OS::Octavia::PoolMember
    depends_on: [wait_for_instance, VDU1]
    properties:
      pool: { get_param: lb_pool }
      address: { get_attr: [VDU1_CP1, fixed_ips, 0, ip_address] }
      protocol_port: 80
      subnet: { get_param: subnet1 }

  # TCP Load Balancer Member
  LB_member_tcp:
    type: OS::Octavia::PoolMember
    depends_on: [wait_for_instance, VDU1]
    condition: has_tcp_pool
    properties:
      pool: { get_param: lb_pool_tcp }
      address: { get_attr: [VDU1_CP1, fixed_ips, 0, ip_address] }
      protocol_port: 8080
      subnet: { get_param: subnet1 }

  # UDP Load Balancer Member
  LB_member_udp:
    type: OS::Octavia::PoolMember
    depends_on: [wait_for_instance, VDU1]
    condition: has_udp_pool
    properties:
      pool: { get_param: lb_pool_udp }
      address: { get_attr: [VDU1_CP1, fixed_ips, 0, ip_address] }
      protocol_port: 53
      subnet: { get_param: subnet1 }

  # Floating IP, remove this when deploying in a public cloud
  VDU1_floatingIP:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: public
      port_id: { get_resource: VDU1_CP1 }

  VDU1_wait: # wait for VDU1 to be ready
    type: OS::Heat::TestResource
    properties:
      action_wait_secs:
        update: 300
      value: { get_resource: VDU1 }

outputs:
  lb_member:
    description: HTTP LB member details.
    value: { get_attr: [LB_member, show] }
  lb_member_tcp:
    description: TCP LB member details.
    value:
      if:
        - has_tcp_pool
        - { get_attr: [LB_member_tcp, show] }
        - "Not configured"
  lb_member_udp:
    description: UDP LB member details.
    value:
      if:
        - has_udp_pool
        - { get_attr: [LB_member_udp, show] }
        - "Not configured"
  instance_id:
    description: "ID of VDU1"
    value: { get_resource: VDU1 }
  vdu1_private_ip:
    description: "Private IP of VDU1"
    value: { get_attr: [VDU1_CP1, fixed_ips, 0, ip_address] }
  vdu1_floating_ip:
    description: "Floating IP of VDU1"
    value: { get_attr: [VDU1_floatingIP, floating_ip_address] }
